#!/bin/bash
#usage : clibc pwn_file libc_version libc_dir
#usage_example: clibc pwn 2.27 ~/glibc-all-in-one/libs/2.27-3ubuntu1.3_amd64
FILE_NAME=$1
LIBC_VERSION=$2

EBIT=$(file $FILE_NAME |awk '{print$3}'|cut -c 1-2)
if [ $EBIT -eq "32" ];then
    LIBC_DIR=/usr/lib/freelibs/i386
elif [ $EBIT -eq "64" ];then
    LIBC_DIR=/usr/lib/freelibs/amd64
else
    echo "It's not a elf file"
    exit
fi
libc_dir=$(find $LIBC_DIR -name "$LIBC_VERSION*")
if [ "$libc_dir" = "" ];then
    echo "Not support version or your $LIBC_DIR don't have libc"
    exit
fi
if  [ "$3" ] 
then
    patchelf --set-interpreter $3/ld-$LIBC_VERSION.so --set-rpath $3/ $1
else
    patchelf --set-interpreter $libc_dir/ld-$LIBC_VERSION.so --set-rpath $libc_dir/ $1
fi
echo "success!!!"