#!/bin/bash
FILE_NAME=$1
LIBC_VERSION=$2
if [ "$FILE_NAME" = "" ];then
	printf "Usage <%s> : clibc <file> <version> <dir>\n"
	printf "Please input the file\n"
	exit
fi
if [ "$LIBC_VERSION" = "" ];then
	printf "Usage <%s> : clibc <file> <version> <dir>\n"
	printf "Please input libc version\n"
	exit
fi
LIBC_DIR=~/glibc-all-in-one/libs
libc_dir=$(find $LIBC_DIR -name "$LIBC_VERSION*")
if [ "$libc_dir" = "" ];then
    echo "Not support version or your $LIBC_DIR don't have libc"
    exit
fi
if  [ "$3" ] 
then
	patchelf --set-interpreter $3/ld-$LIBC_VERSION.so --set-rpath $3/ $1
	echo "success!!!"
else
	printf '%s\n' "$libc_dir"
	echo -e '\033[32mPlease specify the directory \033[0m'
fi
